sudo: false
dist: trusty
language: node_js
services:
  - mongodb
node_js:
  - "8"
install:
  - npm install
script:
  - npm run test
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"